"""add phone to users

Revision ID: e99ebead88a5
Revises: 4ce7262832da
Create Date: 2026-09-22 23:39:13.980088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99ebead88a5'
down_revision: Union[str, Sequence[str], None] = '4ce7262832da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Se agrega nullable primero para no romper filas ya existentes (usuarios
    # seed sin teléfono), se backfillea con un placeholder y recién ahí se
    # exige NOT NULL.
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.execute("UPDATE users SET phone = 'sin-datos' WHERE phone IS NULL")
    op.alter_column('users', 'phone', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
